### PR TITLE
feat: ⚡️ add bin name support

### LINKED ISSUE #20: [bug] Cannot build when the crate and bin name differ
Hi,

Thanks for this plugin.
There is a small quirk it seems that `--bin xxx` is hardcoded into the build executor?

I'm trying to build a bin from a crate but their name differ.
Could this be a configuration option for the executor?

Thanks

### PR DESCRIPTION
**Pull request by melMass**
Fixes #20

### CODE REVIEW

**Comment by dannymcgee** [comment]
Hey @melMass, thanks for the PR, and sorry for the long delay! Taking a look at this now.

**Comment by melMass** [comment]
Great timing! I'm working again on the project I needed this PR for :)

**Comment by dannymcgee** [comment]
Hi @melMass, thanks again for this PR and the bug report! I didn't hear back from you about the comments I left, and there were some other changes that I wanted to make in the meantime, so I went ahead and incorporated a fix for #20 into another PR, which I just merged. I'm going to close this now that the issue has been addressed, but please let me know if you run into any other issues!

**Comment by melMass** [comment]
I saw, much better, great to see it maintained 💪

**Pull request closed without merging**
